export const DEFAULT_ACTIVITY_TITLES: string[] = [
  // Kegiatan ver 1
  "Pelayanan Posyandu",
  "Pelaksanaan Posbindu",
  "Pelacakan dan pengawasan minum obat untuk ODGJ Berat",
  "Deteksi dini dan cek kesehatan gratis di masyarakat",
  "Pemantauan dan tindak lanjut penyakit tidak menular",
  "Pelaksanaan skrining dan intervensi hasil skrining masalah Kesehatan jiwa di UKBM/Lembaga",
  "Pelaksanaan Imunisasi Bayi dan baduta di posyandu",
  "Pelayanan Imunisasi Kejar",
  "Pemeriksaan Jentik Nyamuk",
  "Larvasidasi DBD",
  "Inspeksi Kesehatan Lingkungan di sarana fasilitas umum",
  "Inpeksi Kesehatan Lingkungan di Sarana Air Minum",
  "Inspeksi Kesehatan Lingkungan di Sarana Tempat Pengolahan Pangan",
  "Inspeksi Kesehatan Lingkungan di Sarana Fasyankes",
  "Pemberdayaan kader masyarakat melalui pemicun untuk implementasi pilar 2-5 STBM",
  "Monitoring Pemberdayaan kader masyarakat melalui pemicuan untuk implementasi pilar 2-5 STBM",
  "Kunjungan Lapangan Bumil Masalah Gizi",
  "Kunjungan Lapangan Bayi Balita Masalah Gizi",
  "Pelaksanaan Kelas ibu hamil",
  "Pelaksanaan Kelas ibu balita",
  "Pelayanan UKK",
  "Skrining Kesehatan di sekolah",
  "Pembinaan Kesehatan di sekolah",

  // Tambahan Kegiatan
  "Pelayanan Posyandu Kubangsari",
  "PIKET PERSALINAN PAGI",
  "PIKET PERSALINAN SORE",
  "PIKET PERSALINAN MALAM",
  "LIBUR PIKET PERSALINAN",
  "Pelayanan Posyandu Sinargalih",
  "Pelayanan Posyandu Malingping",
  "Pelayanan Posyandu Selaawi",
  "Pelayanan Posyandu Kadupandak",
  "Pelayanan Posyandu Sindangreret",
  "Pelayanan Posyandu Ciatal",
  "Pelayanan Posyandu Sidamulih",
  "Pelayanan Posyandu Ciharashas",
  "Pelayanan Posyandu Kharisma",
  "Pelayanan Posyandu Bandung",
  "Pelayanan Posyandu Cieurih",
  "Pelayanan Posyandu Puri Sumelap",
  "Pelayanan Posyandu Cibeureum",
  "Pelayanan Posyandu Situhiang",
  "Pelayanan Posyandu Bbk.Cipasung",
  "Pelayanan Posyandu Babakan Jati",
  "Pelayanan Posyandu Nagarasari",
  "Pelayanan Posyandu Ciledug",
  "Pelayanan Posyandu Nangela",
  "Pelayanan Posyandu Sumelap",
  "Pelayanan Posyandu Situdukun",
  "Pelayanan Posyandu Selakaso",
  "Pelayanan Posyandu Gegernoong",
  "Pelayanan Posyandu Cipamutih",
  "Pelayanan Posyandu Jatiwangi",
  "Pelayanan Posyandu Taman",
  "Pelayanan Posyandu Sangkali",
  "Pelayanan Posyandu Liunggunung",
  "Pelayanan Posyandu Harapan Bunda",
  "Pelayanan Posyandu Sukaasih",
  "Pelayanan Posyandu Kasih Bunda",
  "Pelayanan Posyandu Ciangir",
  "Pelayanan Posyandu Perum Sukawening",
  "Pelayanan Posyandu Cidahu",
  "Pelayanan Posyandu Cipasung",
  "Pelayanan Posyandu Cigintung",
  "Pelayanan Posyandu Perum Nusa Indah",
  "Pelayanan Posyandu Kubang",
  "Pelayanan Posyandu Cipangebak",
  "Pelayanan Posyandu Cipajaran",
  "Pelayanan UKK di CV.Katumbiri",
  "Pelayanan UKK di Pasar Gegernoong",
  "Pelayanan UKK di SPPG Muhammadiyah Tamansari",
  "Pelayanan di Pos Yandu Remaja Kereta",
  "Pelayanan di Pos Yandu Remaja Sakura",
  "PENDAFTARAN",
  "SKRINING ILP 1",
  "SKRINING ILP 2",
  "POLI PROLANIS",
  "KLASTER DEWASA-LANSIA 1",
  "KLASTER DEWASA-LANSIA 2",
  "KLASTER IBU KIA & USG",
  "KLASTER ANAK",
  "R. TINDAKAN",
  "R. IMUNISASI",
  "R. TB",
  "BP GIGI",
  "APOTEK",
  "LAB",
  "ADMINSITRASI",
  "PUSTU CIANGIR",
  "PUSTU SUMELAP",
  "Pelaksanaan Posbindu Sidamulih",
  "Pelaksanaan Posbindu Cibeureum",
  "Pelaksanaan Posbindu Sindangreret",
  "Pelaksanaan Posbindu Sumelap",
  "Pelaksanaan Posbindu Cipamutih",
  "Pelaksanaan Posbindu Jatiwangi",
  "Pelaksanaan Posbindu Nagarasari",
  "Pelaksanaan Posbindu Taman",
  "Pelaksanaan Posbindu Cidahu",
  "Pelaksanaan Posbindu Cigintung",
  "Pelaksanaan Posbindu Perum Tamanjaya",
  "Tindak Lanjut Kunjungan Rumah UPKD/K",
  "Penemuan Kasus KIPI",
  "Penemuan Kasus Aktif TB",
  "Penemuan dan tindak lanjut penyakit tropis terabaikan",
  "Penemuan kasus dan deteksi dini pneumonia",
  "PSN oleh kader G1R1J",
  "Penyelidikan Epidimiologi Penyakit Zoonosis",
  "Penyelidikan Epidimiologi Penyakit Arbovirosis",
  "Verifikasi Sinyal penyakit potensial wabah/KLB",
  "Penyeldikan Kasus Epidemiologi Penyakit Kasus Penyakit menular",
  "Surveilans Kualitas Air Minum Rumah Tangga (KAMRT)",
  "Pengasapan Atau Fogging Nyamuk",
  "Pemantauan status bayi dari ibu positif HIV/sifilis",
  "Pemantauan bayi usia 9-12 bulan yang lahir dar ibu Hepatitis B",
  "Kunjungan ulang 60 hari AFP",
  "Pelacakan Kasus Mangkir",
  "Investigasi Kasus TB",
  "Pemantauan minum obat dan terapi pencegahan TBC",
  "Sosialisasi Penyelenggaraan Imunisasi",
  "Pendampingan rujukan balita stunting/gizi buruk",
  "Pembinaan Kesehatan di Komunitas",
  "Fasilitasi pelaksanaan First Aider Pertolongan Pertama pada Luka Psikologis (P3LP) di sekolah",
  "Pemantauan minum obat pneumonia ( care seeking pneumonia )",
  "Pendampingan pelaksanaan ILP di pustu dan Unit Pelayanan Kesehatan Desa/Kelurahan (UPKD/K)",
  "Pengambilan sampel BPSPAM",
  "Pengambilan sampel MBG (Makan bergizi gratis)",
  "Surveilans Migrasi Malaria",
  "Pelaksanaan Survey Cepat Komunitas ( SCK )",
  "Perivikasi Pemberdayaan kader masyarakat melalui pemicuan untuk implementasi pilar 2-5 STBM",
  "Loka karya mini bulanan",
  "Loka karya mini lintas sektor",
];

export const DEFAULT_LOCATIONS: string[] = [
  // Lokasi ver 1
  "Posyandu Kubangsari", 
  "Posyandu Kubang", 
  "Posyandu Gegernoong", 
  "Posyandu Jatiwangi",
  "Posyandu Nyantong", 
  "Posyandu Harapan Bunda", 
  "Posyandu Kasih Bunda", 
  "Posyandu Situdukun",
  "Posyandu Situhiang", 
  "Posyandu Cigintung", 
  "Posyandu Sangkali", 
  "Posyandu Perum Puri Sumelap",
  "Posyandu Sumelap", 
  "Posyandu Cieurih", 
  "Posyandu Sukaasih", 
  "Posyandu Selaawi",
  "Posyandu Bandung", 
  "Posyandu Sidamulih", 
  "Posyandu Babakan Jati", 
  "Posyandu Nagarasari",
  "Posyandu Ciharashas", 
  "Posyandu Ciatal", 
  "Posyandu Selakaso", 
  "Posyandu Karisma",
  "Posyandu Cipasung", 
  "Posyandu Sinargalih", 
  "Posyandu Bantarsari", 
  "Posyandu Malingping",
  "Posyandu Kadupandak", 
  "Posyandu Ciledug", 
  "Posyandu Cipajaran", 
  "Posyandu Cipamutih",
  "Posyandu Nangela", 
  "Posyandu Remaja Sakura", 
  "Posyandu Remaja Kereta",
  "MI Al-Hidayah", 
  "MTs Al-Hidayah", 
  "MA Al-Hidayah", 
  "MA Addriyah",
  "MTs Riyadul Muta'alimin", 
  "SMP Bustanul Ulum",
  "Kampung Sindangreret", 
  "Kampung Selakaso", 
  "Kampung Karanganyar", 
  "Kampung Sinargalih",
  "Kampung Cieurih Girang", 
  "Kampung Cilampahan", 
  "Kampung Cikadongdong", 
  "Kampung Sukasindang",
  "Pasar Gegernoong", 
  "CV. Katumbiri", 
  "SPPG Muhammadiyah Tamansari",
  "Perum Tamanjaya", 
  "Perum Sukawening", 
  "Perum Nusa Indah",
  "Puskesmas",
  "Tamanjaya",
  "Tamansari",
  "Mugarsari",
  "Sumelap",
  "Posyandu Kubangsari",
  "Posyandu Sinargalih",
  "Posyandu Malingping",
  "Posyandu Selaawi",
  "Posyandu Kadupandak",
  "Posyandu Sindangreret",
  "Posyandu Ciatal",
  "Posyandu Sidamulih",
  "Posyandu Ciharashas",
  "Posyandu Kharisma",
  "Posyandu Bandung",
  "Posyandu Cieurih",
  "Posyandu Puri Sumelap",
  "Posyandu Cibeureum",
  "Posyandu Situhiang",
  "Posyandu Bbk.Cipasung",
  "Posyandu Babakan Jati",
  "Posyandu Nagarasari",
  "Posyandu Ciledug",
  "Posyandu Nangela",
  "Posyandu Sumelap",
  "Posyandu Situdukun",
  "Posyandu Selakaso",
  "Posyandu Gegernoong",
  "Posyandu Cipamutih",
  "Posyandu Jatiwangi",
  "Posyandu Taman",
  "Posyandu Sangkali",
  "Posyandu Liunggunung",
  "Posyandu Harapan Bunda",
  "Posyandu Sukaasih",
  "Posyandu Kasih Bunda",
  "Posyandu Ciangir",
  "Posyandu Perum Sukawening",
  "Posyandu Cidahu",
  "Posyandu Cipasung",
  "Posyandu Cigintung",
  "Posyandu Perum Nusa Indah",
  "Posyandu Kubang",
  "Posyandu Cipangebak",
  "Posyandu Cipajaran",
  "Posyandu Sindangreret RW 05",
  "Posbindu Sukaasih",
  "SMP Bustanul Ulum",
  "MTS Al Hidayah",
  "MA Al Hidayah",
  "MA Addriyah",
  "MTS Riyadul muta'alimin",
  "CV.Katumbiri",
  "Pasar Gegernoong",
  "SPPG Muhammadiyah Tamansari",
  "RS TMC",
  "CIHIDEUNG",
  "Posy Kereta",
  "Posyandu Remaja Kreta",
  "Posyandu Remaja Sakura",
];

export const DEFAULT_UPLOADERS: string[] = [
  "Bdn. Yeni Yulyani Setianingsih, S.ST",
  "Bdn. Nina Ainun, S.Tr.Keb",
  "Rita Sahara, S.Tr.Keb",
  "Dewi Sri Mulyani, Am.Keb",
  "Pipit Puspitasari, Am.Keb",
  "Mira Jatnikawati, Am.Keb",
  "Reni Mustikasari, Am.Keb",
  "Alitsa Nuur Fithri, S.ST",
  "Yesi Apriyani, Am.Keb",
  "Asri Awulan, S.Tr.Keb",
  "Pia Nur Podiana, A.Md.Keb",
  "Intang Sri Purnama, AM.Keb",
  "Ucu Lestari, AM.Keb",
  "Annisa Nafaulloh, S.Tr.Keb., Bdn",
  "Mutia Wulansari., S.Kep., Ners",
  "Ujang Effendi, S.Kep., Ners",
  "Liska Permatasari, S.Kep., Ners",
  "Dede Khaerul Kamal Muchtar, AMK",
  "Iman Nurul Haq, A.Md.Kep",
  "Wida Idul Adha, S.Kep., Ners",
  "Oriany Kemala Dewi, Amd.Kep",
  "Haeriah, A.Md.Kep",
  "Dede Aan Septiantini, A.Md.Kep",
  "dr. Ferry Nalapraya",
  "dr. Muhammad Azhary Romdhon",
  "dr. Iwan Setiawan",
  "dr. Siti Hana Fukui",
  "dr. Volti Diana Suryawadi",
  "drg. Rifan Hanggoro.M.M.R.S",
  "Endah Setiawati, S.Tr.Kes",
  "Khilman Husna Pratama, S.Farm., Apt",
  "Vita Tyana Virista, A.Md.AK",
  "Gina Giovany, A.Md.AK",
  "Eko Wahyu Saputro, S.K.M",
  "Nurul Hasanah, A.Md.KL",
  "Nova Silpiany Perdany, A.Md.Farm",
  "Ameilia Putri Isyari, S.Gz",
  "Annisa Fauziah, A.Md.Gz",
  "Rudi Sutikno, SKM",
  "Yogi Aris Diyanto, S.E",
  "Rangga Ismardana Gasbela, S.T",
  "Winda Siti Sarah, AMd.RMIK",
  "Pupung Juliana",
  "Salsa Sabila",
  "Andina Dea Priatna, SKM",
  "Iip Supyan",
  "dr. Hana",
  "dr. Volti",
  "drg.Rifan Hanggoro.M.M.R.S",
  "Dede Khaerul Kamal Muchtar, AMK",
  "Iman Nurul Haq, A.Md.Kep",
  "Wida Idul Adha, S.Kep.,Ners",
  "Asri Awulan, S.Tr.Keb",
  "Yesi Apriyani, Am.Keb",
  "Annisa Nafaulloh.S.Tr.Keb",
  "Rita Sahara, S.Tr.Keb",
  "Reni Mustikasari, Am.Keb",
  "Mira Jatnikawati, Am.Keb",
  "Pipit Puspitasari, Am.Keb",
  "Bdn. Nina Ainun, S.Tr.Keb",
  "Bdn. Yeni Yulyani Setianingsih, S.ST",
  "Pia Nur Podiana, A.Md.Keb",
  "Dewi Sri Mulyani, Am.Keb",
  "Intang Sri Purnama, AM.Keb",
  "Ucu Lestari, A.Md.Keb",
  "Alitsa Nuur Fithri, S.ST",
  "Oriany Kemala Dewi, Amd.Kep",
  "Mutia Wulansari.,S.Kep.,Ners",
  "Liska Permatasari, S.Kep.,Ners",
  "Ujang Effendi, S.Kep.,Ners",
  "Haeriah, A.Md.Kep",
  "Dede Aan Septiantini, A.Md.Kep",
  "Eko Wahyu Saputro, S.K.M",
  "Nurul Hasanah, A.Md.KL",
  "Vita Tyana Virista, A.Md.AK",
  "Gina Giovany, A.Md.AK",
  "Khilman Husna Pratama, S.Farm.,Apt",
  "Nova Silpiany Perdany, A.Md.Farm",
  "Annisa Fauziah, A.Md.Gz",
  "Rudi Sutikno, SKM",
  "Isep Suhendar,SKM",
  "dr.Ferry Nalapraya",
  "dr.Muhammad Azhary Romdhon",
  "dr.Iwan Setiawan",
  "dr. Volti",
  "dr. Hana",
  "drg.Rifan Hanggoro.M.M.R.S",
  "Endah Setiawati,S.Tr.Kes",
  "Ameilia Putri Isyari, S.Gz",
  "Andina Dea Priatna, SKM",
  "Yogi Aris Diyanto, S.E",
  "Rangga Ismardana Gasbela,S.T",
  "Salsa Sabila",
  "Winda Siti Sarah, AMd.RMIK",
  "Pupung Juliana",
];

export const MAX_DESCRIPTION_WORDS = 300;