export const DEFAULT_ACTIVITY_TITLES: string[] = [
  "Pelayanan Posyandu",
  "Pelaksanaan Posbindu",
  "Pelacakan dan pengawasan minum obat untuk ODGJ Berat",
  "Deteksi dini dan cek kesehatan gratis di masyarakat",
  "Pemantauan dan tindak lanjut penyakit tidak menular",
  "Pelaksanaan skrining dan intervensi hasil skrining masalah Kesehatan jiwa di UKBM/Lembaga",
  "Pelaksanaan Imunisasi Bayi dan baduta di posyandu",
  "Pelayanan Imunisasi Kejar",
  "Pemeriksaan Jentik Nyamuk",
  "Larvasidasi DBD",
  "Inspeksi Kesehatan Lingkungan di sarana fasilitas umum",
  "Inpeksi Kesehatan Lingkungan di Sarana Air Minum",
  "Inspeksi Kesehatan Lingkungan di Sarana Tempat Pengolahan Pangan",
  "Inspeksi Kesehatan Lingkungan di Sarana Fasyankes",
  "Pemberdayaan kader masyarakat melalui pemicun untuk implementasi pilar 2-5 STBM",
  "Monitoring Pemberdayaan kader masyarakat melalui pemicuan untuk implementasi pilar 2-5 STBM",
  "Kunjungan Lapangan Bumil Masalah Gizi",
  "Kunjungan Lapangan Bayi Balita Masalah Gizi",
  "Pelaksanaan Kelas ibu hamil",
  "Pelaksanaan Kelas ibu balita",
  "Pelayanan UKK",
  "Skrining Kesehatan di sekolah",
  "Pembinaan Kesehatan di sekolah",
];

export const DEFAULT_LOCATIONS: string[] = [
  "Posyandu Kubangsari", "Posyandu Kubang", "Posyandu Gegernoong", "Posyandu Jatiwangi",
  "Posyandu Nyantong", "Posyandu Harapan Bunda", "Posyandu Kasih Bunda", "Posyandu Situdukun",
  "Posyandu Situhiang", "Posyandu Cigintung", "Posyandu Sangkali", "Posyandu Perum Puri Sumelap",
  "Posyandu Sumelap", "Posyandu Cieurih", "Posyandu Sukaasih", "Posyandu Selaawi",
  "Posyandu Bandung", "Posyandu Sidamulih", "Posyandu Babakan Jati", "Posyandu Nagarasari",
  "Posyandu Ciharashas", "Posyandu Ciatal", "Posyandu Selakaso", "Posyandu Karisma",
  "Posyandu Cipasung", "Posyandu Sinargalih", "Posyandu Bantarsari", "Posyandu Malingping",
  "Posyandu Kadupandak", "Posyandu Ciledug", "Posyandu Cipajaran", "Posyandu Cipamutih",
  "Posyandu Nangela", "Posyandu Remaja Sakura", "Posyandu Remaja Kereta",
  "MI Al-Hidayah", "MTs Al-Hidayah", "MA Al-Hidayah", "MA Addriyah",
  "MTs Riyadul Muta'alimin", "SMP Bustanul Ulum",
  "Kampung Sindangreret", "Kampung Selakaso", "Kampung Karanganyar", "Kampung Sinargalih",
  "Kampung Cieurih Girang", "Kampung Cilampahan", "Kampung Cikadongdong", "Kampung Sukasindang",
  "Pasar Gegernoong", "CV. Katumbiri", "SPPG Muhammadiyah Tamansari",
  "Perum Tamanjaya", "Perum Sukawening", "Perum Nusa Indah",
];

export const DEFAULT_UPLOADERS: string[] = [
  "Bdn. Yeni Yulyani Setianingsih, S.ST",
  "Bdn. Nina Ainun, S.Tr.Keb",
  "Rita Sahara, S.Tr.Keb",
  "Dewi Sri Mulyani, Am.Keb",
  "Pipit Puspitasari, Am.Keb",
  "Mira Jatnikawati, Am.Keb",
  "Reni Mustikasari, Am.Keb",
  "Alitsa Nuur Fithri, S.ST",
  "Yesi Apriyani, Am.Keb",
  "Asri Awulan, S.Tr.Keb",
  "Pia Nur Podiana, A.Md.Keb",
  "Intang Sri Purnama, AM.Keb",
  "Ucu Lestari, AM.Keb",
  "Annisa Nafaulloh, S.Tr.Keb., Bdn",
  "Mutia Wulansari., S.Kep., Ners",
  "Ujang Effendi, S.Kep., Ners",
  "Liska Permatasari, S.Kep., Ners",
  "Dede Khaerul Kamal Muchtar, AMK",
  "Iman Nurul Haq, A.Md.Kep",
  "Wida Idul Adha, S.Kep., Ners",
  "Oriany Kemala Dewi, Amd.Kep",
  "Haeriah, A.Md.Kep",
  "Dede Aan Septiantini, A.Md.Kep",
  "dr. Ferry Nalapraya",
  "dr. Muhammad Azhary Romdhon",
  "dr. Iwan Setiawan",
  "dr. Siti Hana Fukui",
  "dr. Volti Diana Suryawadi",
  "drg. Rifan Hanggoro.M.M.R.S",
  "Endah Setiawati, S.Tr.Kes",
  "Khilman Husna Pratama, S.Farm., Apt",
  "Vita Tyana Virista, A.Md.AK",
  "Gina Giovany, A.Md.AK",
  "Eko Wahyu Saputro, S.K.M",
  "Nurul Hasanah, A.Md.KL",
  "Nova Silpiany Perdany, A.Md.Farm",
  "Ameilia Putri Isyari, S.Gz",
  "Annisa Fauziah, A.Md.Gz",
  "Rudi Sutikno, SKM",
  "Yogi Aris Diyanto, S.E",
  "Rangga Ismardana Gasbela, S.T",
  "Winda Siti Sarah, AMd.RMIK",
  "Pupung Juliana",
  "Salsa Sabila",
  "Andina Dea Priatna, SKM",
  "Iip Supyan",
];

export const MAX_DESCRIPTION_WORDS = 300;